#! /usr/bin/env sh

bspc monitor eDP-1 -d I II III IV

bspc config border_width 1
bspc config bottom_padding 0
bspc config top_padding 0
bspc config focused_border_color "#eceff4"
bspc config window_gap 20

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config click_to_focus true
bspc config swallow_first_click true

bspc rule -a Emacs state=tiled

$HOME/.config/polybar/launch.sh
