#! /bin/sh

xrandr --output eDP-1 --mode 1920x1080 --dpi 210

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config bottom_padding 24
bspc config top_padding 16
bspc config focused_border_color "#eceff4"
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus true
bspc config swallow_first_click true

feh --bg-fill $(find ~/.wallpapers -type f | shuf -n 1)
