#! /bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config border_width         4
bspc config bottom_padding       32
bspc config focused_border_color "#ECEFF4"
bspc config top_padding					 40
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

